export const NATIONALITIES_PT = [
  'Brasileiro(a)',
  'Americano(a)',
  'Argentino(a)',
  'Português(esa)',
  'Espanhol(a)',
  'Italiano(a)',
  'Francês(esa)',
  'Alemão(ã)',
  'Inglês(esa)',
  'Chinês(esa)',
  'Japonês(esa)',
  'Coreano(a)',
  'Mexicano(a)',
  'Canadense',
  'Australiano(a)',
  'Russo(a)',
  'Indiano(a)',
  'Chileno(a)',
  'Colombiano(a)',
  'Peruano(a)',
  'Venezuelano(a)',
  'Uruguaio(a)',
  'Paraguaio(a)',
  'Boliviano(a)',
  'Equatoriano(a)',
];

// Mapa de estados brasileiros para siglas
export const STATE_ABBREVIATIONS: { [key: string]: string } = {
  'Bahia': 'BA',
  'São Paulo': 'SP',
  'Rio de Janeiro': 'RJ',
  'Distrito Federal': 'DF',
  'Ceará': 'CE',
  'Minas Gerais': 'MG',
  'Amazonas': 'AM',
  'Paraná': 'PR',
  'Pernambuco': 'PE',
  'Rio Grande do Sul': 'RS',
  'Pará': 'PA',
  'Goiás': 'GO',
  'Santa Catarina': 'SC',
  'Maranhão': 'MA',
  'Alagoas': 'AL',
  'Piauí': 'PI',
  'Mato Grosso do Sul': 'MS',
  'Mato Grosso': 'MT',
  'Sergipe': 'SE',
  'Espírito Santo': 'ES',
  'Paraíba': 'PB',
  'Amapá': 'AP',
  'Acre': 'AC',
  'Rio Grande do Norte': 'RN',
  'Rondônia': 'RO',
  'Roraima': 'RR',
  'Tocantins': 'TO',
};

export const NATIONALITIES_EN = [
  'Brazilian',
  'American',
  'Argentine',
  'Argentinian',
  'Portuguese',
  'Spanish',
  'Italian',
  'French',
  'German',
  'English',
  'British',
  'Chinese',
  'Japanese',
  'Korean',
  'Mexican',
  'Canadian',
  'Australian',
  'Russian',
  'Indian',
  'Chilean',
  'Colombian',
  'Peruvian',
  'Venezuelan',
  'Uruguayan',
  'Paraguayan',
  'Bolivian',
  'Ecuadorian',
];

export const BRAZILIAN_CITIES = [
  'Salvador, Bahia',
  'São Paulo, São Paulo',
  'Rio de Janeiro, Rio de Janeiro',
  'Brasília, Distrito Federal',
  'Fortaleza, Ceará',
  'Belo Horizonte, Minas Gerais',
  'Manaus, Amazonas',
  'Curitiba, Paraná',
  'Recife, Pernambuco',
  'Porto Alegre, Rio Grande do Sul',
  'Belém, Pará',
  'Goiânia, Goiás',
  'Guarulhos, São Paulo',
  'Campinas, São Paulo',
  'São Luís, Maranhão',
  'São Gonçalo, Rio de Janeiro',
  'Maceió, Alagoas',
  'Duque de Caxias, Rio de Janeiro',
  'Natal, Rio Grande do Norte',
  'Teresina, Piauí',
  'Campo Grande, Mato Grosso do Sul',
  'São Bernardo do Campo, São Paulo',
  'Nova Iguaçu, Rio de Janeiro',
  'João Pessoa, Paraíba',
  'Santo André, São Paulo',
  'Osasco, São Paulo',
  'Jaboatão dos Guararapes, Pernambuco',
  'São José dos Campos, São Paulo',
  'Ribeirão Preto, São Paulo',
  'Uberlândia, Minas Gerais',
  'Sorocaba, São Paulo',
  'Contagem, Minas Gerais',
  'Aracaju, Sergipe',
  'Feira de Santana, Bahia',
  'Cuiabá, Mato Grosso',
  'Joinville, Santa Catarina',
  'Juiz de Fora, Minas Gerais',
  'Londrina, Paraná',
  'Aparecida de Goiânia, Goiás',
  'Niterói, Rio de Janeiro',
  'Ananindeua, Pará',
  'Belford Roxo, Rio de Janeiro',
  'Campos dos Goytacazes, Rio de Janeiro',
  'Caxias do Sul, Rio Grande do Sul',
  'Macapá, Amapá',
  'Vila Velha, Espírito Santo',
  'Florianópolis, Santa Catarina',
  'Vitória, Espírito Santo',
  'Carapicuíba, São Paulo',
  'Vitória da Conquista, Bahia',
];

export const INTERNATIONAL_CITIES_PT = [
  'Lisboa, Portugal',
  'Porto, Portugal',
  'Madrid, Espanha',
  'Barcelona, Espanha',
  'Paris, França',
  'Londres, Inglaterra',
  'Roma, Itália',
  'Milão, Itália',
  'Nova York, EUA',
  'Los Angeles, EUA',
  'Buenos Aires, Argentina',
  'Santiago, Chile',
  'Lima, Peru',
  'Bogotá, Colômbia',
  'Cidade do México, México',
  'Tóquio, Japão',
  'Pequim, China',
  'Seul, Coreia do Sul',
  'Sydney, Austrália',
  'Toronto, Canadá',
];

export const INTERNATIONAL_CITIES_EN = [
  'Lisbon, Portugal',
  'Porto, Portugal',
  'Madrid, Spain',
  'Barcelona, Spain',
  'Paris, France',
  'London, England',
  'Rome, Italy',
  'Milan, Italy',
  'New York, USA',
  'Los Angeles, USA',
  'Buenos Aires, Argentina',
  'Santiago, Chile',
  'Lima, Peru',
  'Bogota, Colombia',
  'Mexico City, Mexico',
  'Tokyo, Japan',
  'Beijing, China',
  'Seoul, South Korea',
  'Sydney, Australia',
  'Toronto, Canada',
];

export const ALL_BIRTHPLACES_PT = [...BRAZILIAN_CITIES, ...INTERNATIONAL_CITIES_PT];
export const ALL_BIRTHPLACES_EN = [...BRAZILIAN_CITIES, ...INTERNATIONAL_CITIES_EN];

export const SALVADOR_NEIGHBORHOODS = [
  'Pituba',
  'Barra',
  'Ondina',
  'Rio Vermelho',
  'Graça',
  'Vitória',
  'Canela',
  'Campo Grande',
  'Brotas',
  'Itaigara',
  'Caminho das Árvores',
  'Costa Azul',
  'Armação',
  'Imbuí',
  'Amaralina',
  'Federação',
  'Horto Florestal',
  'Jardim Apipema',
  'Acupe de Brotas',
  'Garcia',
  'Barris',
  'Nazaré',
  'Comércio',
  'Centro',
  'Cidade Baixa',
  'Liberdade',
  'São Caetano',
  'Cajazeiras',
  'Pau da Lima',
  'Tancredo Neves',
  'Pernambués',
  'Cabula',
  'Saramandaia',
  'Stiep',
  'Paralela',
  'Patamares',
  'Piatã',
  'Itapuã',
  'Stella Maris',
  'Praia do Flamengo',
  'Jardim dos Namorados',
  'Jardim Armação',
  'Boca do Rio',
  'Lauro de Freitas',
  'Vilas do Atlântico',
  'Itinga',
  'Buraquinho',
];
