export const NATIONALITIES_PT = [
  'Brasileiro(a)',
  'Americano(a)',
  'Argentino(a)',
  'Português(esa)',
  'Espanhol(a)',
  'Italiano(a)',
  'Francês(esa)',
  'Alemão(ã)',
  'Inglês(esa)',
  'Chinês(esa)',
  'Japonês(esa)',
  'Coreano(a)',
  'Mexicano(a)',
  'Canadense',
  'Australiano(a)',
  'Russo(a)',
  'Indiano(a)',
  'Chileno(a)',
  'Colombiano(a)',
  'Peruano(a)',
  'Venezuelano(a)',
  'Uruguaio(a)',
  'Paraguaio(a)',
  'Boliviano(a)',
  'Equatoriano(a)',
];

export const NATIONALITIES_EN = [
  'Brazilian',
  'American',
  'Argentine',
  'Argentinian',
  'Portuguese',
  'Spanish',
  'Italian',
  'French',
  'German',
  'English',
  'British',
  'Chinese',
  'Japanese',
  'Korean',
  'Mexican',
  'Canadian',
  'Australian',
  'Russian',
  'Indian',
  'Chilean',
  'Colombian',
  'Peruvian',
  'Venezuelan',
  'Uruguayan',
  'Paraguayan',
  'Bolivian',
  'Ecuadorian',
];

export const BRAZILIAN_CITIES = [
  'Salvador, BA',
  'São Paulo, SP',
  'Rio de Janeiro, RJ',
  'Brasília, DF',
  'Fortaleza, CE',
  'Belo Horizonte, MG',
  'Manaus, AM',
  'Curitiba, PR',
  'Recife, PE',
  'Porto Alegre, RS',
  'Belém, PA',
  'Goiânia, GO',
  'Guarulhos, SP',
  'Campinas, SP',
  'São Luís, MA',
  'São Gonçalo, RJ',
  'Maceió, AL',
  'Duque de Caxias, RJ',
  'Natal, RN',
  'Teresina, PI',
  'Campo Grande, MS',
  'São Bernardo do Campo, SP',
  'Nova Iguaçu, RJ',
  'João Pessoa, PB',
  'Santo André, SP',
  'Osasco, SP',
  'Jaboatão dos Guararapes, PE',
  'São José dos Campos, SP',
  'Ribeirão Preto, SP',
  'Uberlândia, MG',
  'Sorocaba, SP',
  'Contagem, MG',
  'Aracaju, SE',
  'Feira de Santana, BA',
  'Cuiabá, MT',
  'Joinville, SC',
  'Juiz de Fora, MG',
  'Londrina, PR',
  'Aparecida de Goiânia, GO',
  'Niterói, RJ',
  'Ananindeua, PA',
  'Belford Roxo, RJ',
  'Campos dos Goytacazes, RJ',
  'Caxias do Sul, RS',
  'Macapá, AP',
  'Vila Velha, ES',
  'Florianópolis, SC',
  'Vitória, ES',
  'Carapicuíba, SP',
  'Vitória da Conquista, BA',
];

export const INTERNATIONAL_CITIES_PT = [
  'Lisboa, Portugal',
  'Porto, Portugal',
  'Madrid, Espanha',
  'Barcelona, Espanha',
  'Paris, França',
  'Londres, Inglaterra',
  'Roma, Itália',
  'Milão, Itália',
  'Nova York, EUA',
  'Los Angeles, EUA',
  'Buenos Aires, Argentina',
  'Santiago, Chile',
  'Lima, Peru',
  'Bogotá, Colômbia',
  'Cidade do México, México',
  'Tóquio, Japão',
  'Pequim, China',
  'Seul, Coreia do Sul',
  'Sydney, Austrália',
  'Toronto, Canadá',
];

export const INTERNATIONAL_CITIES_EN = [
  'Lisbon, Portugal',
  'Porto, Portugal',
  'Madrid, Spain',
  'Barcelona, Spain',
  'Paris, France',
  'London, England',
  'Rome, Italy',
  'Milan, Italy',
  'New York, USA',
  'Los Angeles, USA',
  'Buenos Aires, Argentina',
  'Santiago, Chile',
  'Lima, Peru',
  'Bogota, Colombia',
  'Mexico City, Mexico',
  'Tokyo, Japan',
  'Beijing, China',
  'Seoul, South Korea',
  'Sydney, Australia',
  'Toronto, Canada',
];

export const ALL_BIRTHPLACES_PT = [...BRAZILIAN_CITIES, ...INTERNATIONAL_CITIES_PT];
export const ALL_BIRTHPLACES_EN = [...BRAZILIAN_CITIES, ...INTERNATIONAL_CITIES_EN];

export const SALVADOR_NEIGHBORHOODS = [
  'Pituba',
  'Barra',
  'Ondina',
  'Rio Vermelho',
  'Graça',
  'Vitória',
  'Canela',
  'Campo Grande',
  'Brotas',
  'Itaigara',
  'Caminho das Árvores',
  'Costa Azul',
  'Armação',
  'Imbuí',
  'Amaralina',
  'Federação',
  'Horto Florestal',
  'Jardim Apipema',
  'Acupe de Brotas',
  'Garcia',
  'Barris',
  'Nazaré',
  'Comércio',
  'Centro',
  'Cidade Baixa',
  'Liberdade',
  'São Caetano',
  'Cajazeiras',
  'Pau da Lima',
  'Tancredo Neves',
  'Pernambués',
  'Cabula',
  'Saramandaia',
  'Stiep',
  'Paralela',
  'Patamares',
  'Piatã',
  'Itapuã',
  'Stella Maris',
  'Praia do Flamengo',
  'Jardim dos Namorados',
  'Jardim Armação',
  'Boca do Rio',
  'Lauro de Freitas',
  'Vilas do Atlântico',
  'Itinga',
  'Buraquinho',
];
